name             'sensu_admin'
maintainer       'Fraser Scott'
maintainer_email 'fraser.scott@gmail.com'
license          'MIT'
description      'Installs/Configures sensu_admin'
long_description 'Installs/Configures sensu_admin'
version          '0.1.1'

depends 'apt'
depends 'application_ruby'
depends 'ruby_build'
depends 'runit'
depends 'nginx'
